controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    allow_partial_joints_goal: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
joint_state_broadcaster:
  ros__parameters:
    use_local_topics: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    state_interfaces:
      - position
      - velocity


joint_trajectory_controller:
  ros__parameters:
    allow_partial_joints_goal: true
    
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      