joint_state_publisher:
  ros__parameters:
    robot_description: 
      - robot_description
    source_list: 
      - /joint_state_broadcaster/joint_states
    zeros: 
      joint_1: 1.57
      joint_2: -0.35
      joint_3: -2.00
      joint_4: 0
      joint_5: -1.00
      joint_6: 1.57